# Generated by Django 3.0.6 on 2020-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='Title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
